"""Re-derive every MOANA result the report prints, and diff against it.

The acceptance test for the IOPtics → EPFT-UP move (``claude_prompts/
moana_prompts.md`` Q14/Q18): after the copy and the ``ioptics`` → ``epft_up``
rename, the three completed validation targets and the six report figures
are regenerated from scratch, and every number is set beside the value the
report (``reports/MOANA_Claude_Report.md``, rev. 4) prints. Same conda
environment, fixed seeds, deterministic code, so the pass criterion is
**equality at the report's printed precision** — anything else is a
migration bug to investigate, not a number to update.

Targets re-derived (report §12.2, §12.3, §7.1/§12.4):

* (i)    ``validate_amt24``            — Lange Table 1 on AMT24, CTD-only;
                                         plus the basis recovery |cos| values;
* (ii)   ``validate_heldout_cruises``  — published model on AMT23/25/28;
* (iii-a) ``bitexact_pace``            — which PC mapping the PACE product ships.

Target (iii-b) has no in-situ counts on disk and is not re-derivable.

Run with::

    conda run -n ocean14 python reports/scripts/moana_rederive.py
        [--reference-figs DIR] [--out-dir DIR]

Outputs:
    reports/moana_rederivation.md          -- side-by-side table, PASS/FAIL per number
    $OS_COLOR/EPFT-UP/moana/rederivation_<date>.json
                                           -- every re-derived number, machine-readable
    $OS_COLOR/EPFT-UP/moana/amt24_matchups_<date>.parquet
                                           -- the n = 30 AMT24 training matchups
    reports/figures/moana_*.png            -- regenerated by moana_report_figs.main()

Needs the ``$OS_COLOR`` tree (AMT24 Level-2 + FCM + Jordan SST, Brewin 2023,
AMT23/25/28 FCM, the cached 2025-07-01 PACE granule pair).
"""

import argparse
import datetime as _dt
import json
import os
import sys
import time

import numpy as np
import pandas as pd

# Repo-relative paths, resolved from this script's location so the working
# directory does not matter; the repo root is put on sys.path so the script
# runs without an install (same idiom as moana_report_figs.py).
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, os.pardir, os.pardir))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)
FIG_DIR = os.path.join(_REPO, "reports", "figures")
OUT_MD = os.path.join(_REPO, "reports", "moana_rederivation.md")
#: Where the IOPtics originals of the six figures live on this machine.
DEFAULT_REFERENCE_FIGS = os.path.join(
    os.path.dirname(_REPO), "IOPtics", "reports", "figures")
FIGURES = ("moana_pc_loadings", "moana_product_masks", "moana_clipping",
           "moana_mapping_verdict", "moana_mapping_consequence",
           "moana_heldout_skill")
TAXA = ("pro", "syn", "peuk")

# ---------------------------------------------------------------------------
# Reference values, transcribed from reports/MOANA_Claude_Report.md (rev. 4).
# Each entry: (value as printed, section). Printed precision is what the
# comparison rounds to; a (lo, hi) tuple is a printed range.
# ---------------------------------------------------------------------------
REF = {
    # §12.2 — target (i), n = 30 matchups
    "amt24.n": ("30", "§12.2"),
    "amt24.retrained.pro": ("1.01 / 1.22 / 0.77", "§12.2 table, full-fit"),
    "amt24.retrained.syn": ("1.00 / 1.36 / 0.91", "§12.2 table, full-fit"),
    "amt24.retrained.peuk": ("1.00 / 1.19 / 0.97", "§12.2 table, full-fit"),
    "amt24.cv.pro": ("1.25 / 1.78 / 0.25", "§12.2 table, 80/20 CV"),
    "amt24.cv.syn": ("0.68 / 3.34 / -6.5", "§12.2 table, 80/20 CV"),
    "amt24.cv.peuk": ("0.93 / 1.56 / 0.50", "§12.2 table, 80/20 CV"),
    "amt24.published.peuk": ("1.03 / 1.23 / 0.94", "§12.2 transfer experiment"),
    "amt24.published.pro.bias": ("1.96", "§12.2 transfer experiment (+96 %)"),
    "amt24.published.syn.bias": ("0.61", "§12.2 transfer experiment (−39 %)"),
    "amt24.basis.PC1": ("0.999", "§12.2 basis recovery"),
    "amt24.basis.PC2": ("0.998", "§12.2 basis recovery"),
    "amt24.basis.PC3": ((0.96, 0.98), "§12.2 basis recovery (PC3–5 range)"),
    "amt24.basis.PC4": ((0.96, 0.98), "§12.2 basis recovery (PC3–5 range)"),
    "amt24.basis.PC5": ((0.96, 0.98), "§12.2 basis recovery (PC3–5 range)"),
    # §12.3 — target (ii), bias/MAE/R²
    "heldout.23.pro": ("1.20/1.59/-1.8", "§12.3 table"),
    "heldout.25.pro": ("2.47/2.90/0.15", "§12.3 table"),
    "heldout.28.pro": ("3.17/4.07/-0.4", "§12.3 table"),
    "heldout.pooled.pro": ("2.19/2.75/-0.14", "§12.3 table"),
    "heldout.23.syn": ("1.26/1.77/0.71", "§12.3 table"),
    "heldout.25.syn": ("1.08/2.05/0.54", "§12.3 table"),
    "heldout.28.syn": ("0.48/3.90/-10.6", "§12.3 table"),
    "heldout.pooled.syn": ("0.85/2.46/-3.0", "§12.3 table"),
    "heldout.23.peuk": ("0.79/1.40/0.76", "§12.3 table"),
    "heldout.25.peuk": ("1.16/1.58/0.77", "§12.3 table"),
    "heldout.28.peuk": ("1.24/1.43/0.80", "§12.3 table"),
    "heldout.pooled.peuk": ("1.07/1.47/0.78", "§12.3 table"),
    "heldout.n_stations": ("90", "prompt-14 log (stations retrieved)"),
    "heldout.pooled.n": ((66, 71), "§12.3 (66–71 pooled matchups)"),
    # §7.1 SETTLED box / §12.4 — target (iii-a). The box's four numbers are
    # the annotation of figures/moana_mapping_verdict.png (plot_mapping_verdict:
    # 60k-pixel subsample, ``nasa > 0`` mask, no nasa_compat), so they are
    # checked by replicating the figure's method; ``bitexact_pace`` itself
    # (100k pixels, seed 0, nasa_compat) is checked against the prompt-14 log
    # in claude_prompts/moana_IOPtics_history.md, the only record of its output.
    "figmethod.operational.syn.median_dlog": ("-0.005", "§7.1 SETTLED box (figure annotation)"),
    "figmethod.operational.syn.mad_dlog": ("0.007", "§7.1 SETTLED box (figure annotation)"),
    "figmethod.atbd.syn.median_dlog": ("0.082", "§7.1 SETTLED box (figure annotation)"),
    "figmethod.atbd.syn.mad_dlog": ("0.090", "§7.1 SETTLED box (figure annotation)"),
    "pace.operational.syn.median_dlog": ("-0.005", "prompt-14 log (bitexact_pace, 100k)"),
    "pace.operational.syn.mad_dlog": ("0.007", "prompt-14 log (bitexact_pace, 100k)"),
    "pace.atbd.syn.median_dlog": ("0.084", "prompt-14 log (bitexact_pace, 100k)"),
    "pace.atbd.syn.mad_dlog": ("0.090", "prompt-14 log (bitexact_pace, 100k)"),
    "pace.verdict": ("operational", "§7.1 SETTLED box"),
    "pace.operational.syn.frac_exact": ((0.10, 0.14), "§7.1 (~12 % of pixels exact)"),
}


def _decimals(text):
    """Number of decimals a printed value carries ('1.20' → 2, '-6.5' → 1)."""
    return len(text.split(".")[1]) if "." in text else 0


def _fmt(value, text_like):
    """Format ``value`` at the precision of the printed reference ``text_like``."""
    return f"{value:.{_decimals(text_like)}f}"


def check(key, value):
    """Compare one re-derived value against its reference entry.

    Inputs
    ------
    key : str — a key of :data:`REF`.
    value : float | int | str | sequence — the re-derived value. A
        bias/MAE/R² triple is passed as a 3-sequence and compared element-wise
        at each element's printed precision.

    Outputs
    -------
    dict — ``key``, ``section``, ``reference`` (printed), ``rederived``
    (printed at the same precision), ``pass`` (bool).
    """
    ref, section = REF[key]
    if isinstance(ref, tuple):                        # a printed range
        if isinstance(value, float):
            # Compare at the range's own printed precision (report: 2 dp), so
            # 0.983 is inside "0.96–0.98" exactly as a reader would judge it.
            dp = max(_decimals(str(b)) for b in ref)
            shown = f"{value:.{dp}f}"
            ok = ref[0] <= float(shown) <= ref[1]
        else:
            shown, ok = str(value), ref[0] <= value <= ref[1]
        ref_shown = f"{ref[0]}–{ref[1]}"
    elif isinstance(value, str):                      # a categorical verdict
        ok, shown, ref_shown = (value == ref), value, ref
    elif "/" in ref:                                  # bias / MAE / R² triple
        parts = [p.strip() for p in ref.split("/")]
        shown_parts = [_fmt(v, p) for v, p in zip(value, parts)]
        ok = all(float(s) == float(p) for s, p in zip(shown_parts, parts))
        sep = " / " if " / " in ref else "/"
        shown, ref_shown = sep.join(shown_parts), ref
    else:                                             # a single number
        shown = _fmt(value, ref)
        ok, ref_shown = (float(shown) == float(ref)), ref
    return {"key": key, "section": section, "reference": ref_shown,
            "rederived": shown, "pass": bool(ok)}


def _triple(m):
    """(bias, MAE, R²) from a seegers_metrics dict."""
    return (m["bias"], m["mae"], m["r2"])


def rederive_amt24():
    """Target (i) + basis recovery. Returns (results dict, checks list, matchups)."""
    from epft_up.moana.train import compare_loadings
    from epft_up.moana.validation import validate_amt24

    t0 = time.perf_counter()
    res = validate_amt24(verbose=False)
    elapsed = time.perf_counter() - t0
    cmp = compare_loadings(res["model"]["pca"]["V"], n_compare=5)

    out = {"n": int(len(res["matchups"])), "elapsed_s": elapsed,
           "basis_best_cos": [float(c) for c in cmp["best_cos"]],
           "basis_best_match": [int(b) for b in cmp["best_match"]]}
    for mode in ("published", "retrained", "cv"):
        out[mode] = {t: {k: float(v) for k, v in res[mode][t].items()}
                     for t in TAXA}

    checks = [check("amt24.n", out["n"])]
    for t in TAXA:
        checks.append(check(f"amt24.retrained.{t}", _triple(res["retrained"][t])))
    for t in TAXA:
        checks.append(check(f"amt24.cv.{t}", _triple(res["cv"][t])))
    checks.append(check("amt24.published.peuk", _triple(res["published"]["peuk"])))
    checks.append(check("amt24.published.pro.bias", res["published"]["pro"]["bias"]))
    checks.append(check("amt24.published.syn.bias", res["published"]["syn"]["bias"]))
    for i in range(5):
        checks.append(check(f"amt24.basis.PC{i + 1}", float(cmp["best_cos"][i])))
    # "in order": NASA PC i is best matched by our column i.
    out["basis_in_order"] = bool((cmp["best_match"] == np.arange(5)).all())
    return out, checks, res["matchups"]


def rederive_heldout():
    """Target (ii). Returns (results dict, checks list)."""
    from epft_up.moana.io import load_fcm
    from epft_up.moana.validation import validate_heldout_cruises

    t0 = time.perf_counter()
    tables = {c: load_fcm(cruise=c) for c in (23, 25, 28)}
    res = validate_heldout_cruises(fcm_tables=tables, verbose=False)
    elapsed = time.perf_counter() - t0

    out = {"n_stations": int(len(res["retrievals"])), "elapsed_s": elapsed,
           "missing_counts": res["missing_counts"], "metrics": {}}
    checks = [check("heldout.n_stations", out["n_stations"])]
    for cruise in (23, 25, 28, "pooled"):
        rows = res["metrics"][cruise]
        out["metrics"][str(cruise)] = {t: {k: float(v) for k, v in rows[t].items()}
                                       for t in TAXA}
    for t in TAXA:
        for cruise in (23, 25, 28, "pooled"):
            checks.append(check(f"heldout.{cruise}.{t}",
                                _triple(res["metrics"][cruise][t])))
    pooled_n = [res["metrics"]["pooled"][t]["n"] for t in TAXA]
    out["pooled_n"] = [int(n) for n in pooled_n]
    checks.append(check("heldout.pooled.n", int(min(pooled_n))))
    checks.append(check("heldout.pooled.n", int(max(pooled_n))))
    return out, checks


def rederive_pace(max_pixels=100_000):
    """Target (iii-a) on the cached granule pair. Returns (results, checks)."""
    from epft_up.moana.validation import bitexact_pace

    t0 = time.perf_counter()
    res = bitexact_pace(max_pixels=max_pixels, seed=0, verbose=False)
    elapsed = time.perf_counter() - t0
    out = {"max_pixels": max_pixels, "elapsed_s": elapsed,
           "verdict": res["verdict"]}
    for m in ("operational", "atbd"):
        out[m] = {t: {k: float(v) for k, v in res[m][t].items()}
                  for t in ("syn", "peuk")}
    checks = [
        check("pace.operational.syn.median_dlog", res["operational"]["syn"]["median_dlog"]),
        check("pace.operational.syn.mad_dlog", res["operational"]["syn"]["mad_dlog"]),
        check("pace.atbd.syn.median_dlog", res["atbd"]["syn"]["median_dlog"]),
        check("pace.atbd.syn.mad_dlog", res["atbd"]["syn"]["mad_dlog"]),
        check("pace.verdict", res["verdict"]),
        check("pace.operational.syn.frac_exact", res["operational"]["syn"]["frac_exact"]),
    ]
    return out, checks


def rederive_figure_method(n_pixels=60_000, seed=0):
    """Replicate plot_mapping_verdict's annotated statistics (report §7.1 box).

    Inputs
    ------
    n_pixels, seed : the figure's defaults.

    Outputs
    -------
    (results dict, checks list) — per mapping, Synechococcus median Δlog₁₀
    and MAD, computed exactly as the figure does (its own ``nasa > 0``
    subsample, no ``nasa_compat`` truncation).
    """
    import xarray as xr
    import moana_report_figs as figs                # sibling script
    from epft_up.moana import run_moana

    aop = xr.open_dataset(figs.AOP_GRANULE)
    moana = xr.open_dataset(figs.GRANULE)
    rrs = aop["Rrs"].sel(lat=moana["lat"].values, lon=moana["lon"].values,
                         method="nearest", tolerance=1e-3)
    wave = aop["wavelength"].values.astype(float)
    nasa = moana["syncoccus_moana"].values
    valid = np.isfinite(nasa) & (nasa != figs.LAND) & (nasa != figs.FILL) & (nasa > 0)
    iy, ix = np.nonzero(valid)
    pick = np.random.default_rng(seed).choice(iy.size, min(n_pixels, iy.size),
                                              replace=False)
    iy, ix = iy[pick], ix[pick]
    spectra = rrs.values[iy, ix, :]
    theirs = np.log10(nasa[iy, ix].astype(float))
    aop.close(), moana.close()

    out, checks = {"n_pixels": int(iy.size)}, []
    for mapping in ("operational", "atbd"):
        res = run_moana(wave, spectra, sst=None, pc_mapping=mapping)
        ok = np.isfinite(res["syn"]) & (res["syn"] > 0)
        dlog = np.log10(res["syn"][ok]) - theirs[ok]
        out[mapping] = {"median_dlog": float(np.median(dlog)),
                        "mad_dlog": float(np.median(np.abs(dlog)))}
        checks.append(check(f"figmethod.{mapping}.syn.median_dlog", out[mapping]["median_dlog"]))
        checks.append(check(f"figmethod.{mapping}.syn.mad_dlog", out[mapping]["mad_dlog"]))
    return out, checks


def regenerate_and_compare_figures(reference_dir):
    """Rebuild the six figures and compare decoded pixels to the originals.

    Inputs
    ------
    reference_dir : str — directory holding the IOPtics originals.

    Outputs
    -------
    list of dict — per figure: ``exists``, ``same_shape``, ``identical``
    (pixel-exact), ``frac_pixels_differ``, ``max_abs_diff`` (0–255 scale).
    """
    import matplotlib.image as mpimg
    import moana_report_figs                       # sibling script (on sys.path via _HERE)

    t0 = time.perf_counter()
    moana_report_figs.main()
    elapsed = time.perf_counter() - t0

    rows = []
    for name in FIGURES:
        new_path = os.path.join(FIG_DIR, f"{name}.png")
        ref_path = os.path.join(reference_dir, f"{name}.png")
        row = {"figure": name, "exists": os.path.isfile(new_path),
               "reference_exists": os.path.isfile(ref_path)}
        if row["exists"] and row["reference_exists"]:
            a = (mpimg.imread(new_path) * 255).round().astype(np.int16)
            b = (mpimg.imread(ref_path) * 255).round().astype(np.int16)
            row["same_shape"] = a.shape == b.shape
            if row["same_shape"]:
                d = np.abs(a - b)
                row["identical"] = bool((d == 0).all())
                row["frac_pixels_differ"] = float((d.max(axis=-1) > 0).mean())
                row["max_abs_diff"] = int(d.max())
            else:
                row.update(identical=False, frac_pixels_differ=None,
                           max_abs_diff=None, shapes=[list(a.shape), list(b.shape)])
        rows.append(row)
    return rows, elapsed


def write_markdown(path, checks, figs, results, run_date, out_dir):
    """Write the side-by-side acceptance report."""
    # The agreed criterion (Q18) is the numbers the *report* prints. Values
    # that exist only in the IOPtics prompt log are checked too, but listed
    # separately so a log-only difference is visible without being conflated.
    report_checks = [c for c in checks if "log" not in c["section"]]
    log_checks = [c for c in checks if "log" in c["section"]]
    n_pass, n_all = sum(c["pass"] for c in report_checks), len(report_checks)
    log_fail = [c for c in log_checks if not c["pass"]]
    verdict = (f"**PASS** — all {n_all} report-printed numbers match at their printed precision."
               if n_pass == n_all else
               f"**FAIL** — {n_all - n_pass} of {n_all} report-printed numbers differ (rows marked ✗).")
    if log_fail:
        verdict += (f" Of the {len(log_checks)} values recorded only in the IOPtics prompt log, "
                    f"{len(log_fail)} differ: "
                    + "; ".join(f"`{c['key']}` log {c['reference']} vs {c['rederived']}" for c in log_fail)
                    + ".")
    fig_ok = all(f.get("identical") for f in figs)
    lines = [
        "# MOANA re-derivation after the IOPtics → EPFT-UP move",
        "",
        f"**Run:** {run_date} · `reports/scripts/moana_rederive.py` · conda env `ocean14` · "
        f"source imported from IOPtics `moana` @ `3aa3b6e`.",
        "",
        "Acceptance test for the Move (`claude_prompts/moana_prompts.md`, Q14/Q18): "
        "targets (i), (ii) and (iii-a) re-run from the raw inputs under `$OS_COLOR` with the "
        "migrated `epft_up.moana` code, and every number the report prints set beside the "
        "re-derived value at the same precision. Target (iii-b) has no in-situ counts on disk.",
        "",
        f"## Verdict: {verdict}",
        "",
        f"Figures: {'all six pixel-identical to the IOPtics originals' if fig_ok else 'see the figure table — not all pixel-identical'}.",
        "",
        "## Numbers",
        "",
        "| # | quantity | report | re-derived | report section | |",
        "|---|---|---|---|---|---|",
    ]
    for i, c in enumerate(checks, 1):
        lines.append(f"| {i} | `{c['key']}` | {c['reference']} | {c['rederived']} | "
                     f"{c['section']} | {'✓' if c['pass'] else '✗'} |")
    lines += [
        "",
        "Triples are bias / MAE / R² (Seegers et al. 2018 log₁₀-space bias and MAE; R² on the "
        "taxon's model scale). `amt24.basis.PCn` is |cos| between our retrained loading *n* and "
        "NASA's stored PC *n*; in-order match: "
        f"{'yes' if results['amt24']['basis_in_order'] else 'NO'}.",
        "",
        "## Figures (regenerated here vs the IOPtics originals, decoded pixels)",
        "",
        "| figure | pixel-identical | pixels differing | max |Δ| (0–255) |",
        "|---|---|---|---|",
    ]
    for f in figs:
        ident = f.get("identical")
        lines.append(
            f"| `{f['figure']}.png` | {'yes' if ident else 'no' if ident is not None else 'n/a'} | "
            f"{'' if f.get('frac_pixels_differ') is None else f'{100 * f['frac_pixels_differ']:.3f} %'} | "
            f"{'' if f.get('max_abs_diff') is None else f['max_abs_diff']} |")
    lines += [
        "",
        "## Run record",
        "",
        f"- target (i) `validate_amt24`: {results['amt24']['elapsed_s']:.1f} s "
        f"(37-day Level-2 chain + matchup + retraining + 100 bootstrap refits), n = {results['amt24']['n']}",
        f"- target (ii) `validate_heldout_cruises`: {results['heldout']['elapsed_s']:.2f} s, "
        f"{results['heldout']['n_stations']} stations retrieved, pooled n per taxon {results['heldout']['pooled_n']}",
        f"- target (iii-a) `bitexact_pace`: {results['pace']['elapsed_s']:.1f} s on "
        f"{results['pace']['max_pixels']:,} ocean pixels (seed 0), verdict `{results['pace']['verdict']}`",
        f"- target (iii-a), figure method (`plot_mapping_verdict` statistics on "
        f"{results['figure_method']['n_pixels']:,} pixels): operational "
        f"{results['figure_method']['operational']['median_dlog']:+.4f} / MAD "
        f"{results['figure_method']['operational']['mad_dlog']:.4f}; ATBD "
        f"{results['figure_method']['atbd']['median_dlog']:+.4f} / MAD "
        f"{results['figure_method']['atbd']['mad_dlog']:.4f}",
        f"- figures `moana_report_figs.main()`: {results['figures_elapsed_s']:.1f} s",
        f"- machine-readable results and the AMT24 matchup table: `{out_dir}/`",
        "",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--reference-figs", default=DEFAULT_REFERENCE_FIGS,
                        help="directory with the IOPtics originals of the six figures")
    parser.add_argument("--out-dir", default=None,
                        help="where JSON/parquet land (default $OS_COLOR/EPFT-UP/moana)")
    parser.add_argument("--max-pixels", type=int, default=100_000,
                        help="ocean pixels for bitexact_pace (report: 100k)")
    args = parser.parse_args()

    out_dir = args.out_dir or os.path.join(os.environ["OS_COLOR"], "EPFT-UP", "moana")
    os.makedirs(out_dir, exist_ok=True)
    run_date = _dt.date.today().isoformat()

    print("target (i): AMT24 ...")
    amt24, checks, matchups = rederive_amt24()
    print("target (ii): AMT23/25/28 ...")
    heldout, c2 = rederive_heldout()
    checks += c2
    print("target (iii-a): PACE granule pair ...")
    pace, c3 = rederive_pace(args.max_pixels)
    checks += c3
    print("target (iii-a), figure method ...")
    figmethod, c4 = rederive_figure_method()
    checks += c4
    print("figures ...")
    figs, fig_elapsed = regenerate_and_compare_figures(args.reference_figs)

    results = {"run_date": run_date, "source": "IOPtics moana @ 3aa3b6e",
               "amt24": amt24, "heldout": heldout, "pace": pace,
               "figure_method": figmethod,
               "figures": figs, "figures_elapsed_s": fig_elapsed,
               "checks": checks}
    json_path = os.path.join(out_dir, f"rederivation_{run_date}.json")
    with open(json_path, "w") as fh:
        json.dump(results, fh, indent=2, default=str)
    pq_path = os.path.join(out_dir, f"amt24_matchups_{run_date}.parquet")
    matchups.to_parquet(pq_path, index=False)
    write_markdown(OUT_MD, checks, figs, results, run_date, out_dir)

    n_pass = sum(c["pass"] for c in checks)
    print(f"\n{n_pass}/{len(checks)} numbers match their source (report or IOPtics log); "
          f"figures identical: {sum(bool(f.get('identical')) for f in figs)}/{len(figs)}")
    for c in checks:
        if not c["pass"]:
            print(f"  MISMATCH {c['key']}: report {c['reference']} vs {c['rederived']}")
    print(f"wrote {OUT_MD}\n      {json_path}\n      {pq_path}")
    # Exit status follows the agreed criterion: report-printed numbers only.
    report_ok = all(c["pass"] for c in checks if "log" not in c["section"])
    return 0 if report_ok else 1


if __name__ == "__main__":
    sys.exit(main())
